triggers:
  - name: triggerscript 
    type: trigger
    pointer:
       counter: 3
      
      
      
#  - name: triggertest2
 #   type: trigger
  #  source:
   #   message: 'sRRtfggfiffng of sygggggggns2'
    #  counter: 1
      
  #- name: triggertest3
   # type: trigger
  #  source:
   #   message: 'testfFthrfTffhgniRggRnyhthygfg of ssyyjnc3'
    #  counter: 2 
 
